### ISSUE TITLE
Problem Setting up Sloeber

### ISSUE THREAD

**Issue by beemeeup** [stangreg/Ignitron#10]
**Describe the bug**
I have downloaded Sloeber (normally using vscode), but I don´t find the Libraries needed to compile. I always ends up with error because of files not found.

Can you add links to the libraries here in the project Readme? The Table already lists needed libraries. But I can´t find them online.

Thanks!

Matthias

**Comment by stangreg** [comment]
Hi Matthias,

I have added information on where to get the libraries. Most of the libraries can easily be installed by using the Library Manager of the Arduino IDE. As far as I remember, only the BLE Keyboard library had to be installed manually using the GitHub link.

After installing via the IDE, you can easily select the libraries to use for the Sloeber project. Just choose "Add a library to the selected project" in the Arduino menu item.

Please let me know if it worked for you.

Steffen

**Comment by beemeeup** [comment]
Thanks for the fast Reply.
Your changes to the tables helped a lot, but I still was not able to include all libraries. (Also I'm not sure which IDE to go with. Arduino or Sloeber... tried both... same Error)

Didnt find the following:

Update
Webserver
ESPmDNS
FS


I tried to compile with Sloeber anyway and got another Error:

```
.\src\SparkBLEKeyboard.cpp.o:(.rodata._ZTV16SparkBLEKeyboard[vtable for SparkBLEKeyboard]+0x20): undefined reference to `BleKeyboard::onConnect(NimBLEServer*)'
.\src\SparkBLEKeyboard.cpp.o:(.rodata._ZTV16SparkBLEKeyboard[vtable for SparkBLEKeyboard]+0x24): undefined reference to `BleKeyboard::onDisconnect(NimBLEServer*)'
.\src\SparkBLEKeyboard.cpp.o:(.rodata._ZTV16SparkBLEKeyboard[vtable for SparkBLEKeyboard]+0x28): undefined reference to `BleKeyboard::onWrite(NimBLECharacteristic*)'
.\src\SparkBLEKeyboard.cpp.o:(.rodata._ZTV16SparkBLEKeyboard[vtable for SparkBLEKeyboard]+0x3c): undefined reference to `non-virtual thunk to BleKeyboard::onConnect(NimBLEServer*)'
.\src\SparkBLEKeyboard.cpp.o:(.rodata._ZTV16SparkBLEKeyboard[vtable for SparkBLEKeyboard]+0x44): undefined reference to `non-virtual thunk to BleKeyboard::onDisconnect(NimBLEServer*)'
.\src\SparkBLEKeyboard.cpp.o:(.rodata._ZTV16SparkBLEKeyboard[vtable for SparkBLEKeyboard]+0x74): undefined reference to `non-virtual thunk to BleKeyboard::onWrite(NimBLECharacteristic*)'
```
Would be very kind if you could help me to solve my problems. I am still waiting for my Spark to arrive, but I really want this Pedal. I am already in the Process of designing a 3d Printed Case, similar to yours.


Matthias

**Comment by stangreg** [comment]
Regarding the compile error, it seems that you have not set the "USE_NIMBLE" switch in the build options. 
Please check under "Project -> Properties -> Arduino", then select the "Compile Options" tab and check that the field "append to C++" has the value "-D USE_NIMBLE" (without quotes).


Regarding the missing libraries, I cannot recall to have them installed manually, maybe they are part of the default libraries. What can you see when selecting "Arduino -> Add a library to the selected project"?
Mine looks like following:

<img width="401" alt="Bildschirmfoto 2022-04-13 um 12 38 39" src="https://user-images.githubusercontent.com/89360856/163162639-02a39243-ba43-4941-b5a7-e5f46b951efa.png">
<img width="364" alt="Bildschirmfoto 2022-04-13 um 12 43 11" src="https://user-images.githubusercontent.com/89360856/163163822-68e07c5a-c609-4f65-92ed-2232c689e1e6.png">

Regarding which IDE to use, it is up to you. I found it much more easy to write code with Sloeber due to the navigation options and code completion. However, for adding libraries or using the Data Upload (for uploading the initial presets), I use the Arduino IDE.

I hope it works out for you!

**Comment by stangreg** [comment]
Addendum to the previous remark: I have also updated some library versions. Also the code now has a stability update to improve initialization.

**Comment by beemeeup** [comment]
It was the USE_NIMBLE option. Now it´s compiling without Error.
I will try to flash and test it this weekend.

Thanks for your help and very detailed information.
